debug: true

service:
  protocol: "http"
  addr: "172.18.0.2:8080"
  region: "us-est-2"
  accountId: "0000000000"

lambda:
  # if changed, for now the makefile and Docker files must be updated as well
  workfolder: "repo"
