FROM cprates/lws_base:latest as builder

WORKDIR /lws
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo ./cmd/lws \
    && CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo ./cmd/runbox

FROM alpine:3.10
RUN apk --no-cache add ca-certificates
WORKDIR /lws
COPY --from=builder /lws/lws .
COPY --from=builder /lws/config.yaml .
COPY --from=builder /lws/runbox /bin
COPY repo/*_base.tar /lws/repo/

CMD ["/lws/lws"]
EXPOSE 8080