FROM golang:1.14-alpine

WORKDIR /lws

COPY go.mod .

RUN go mod download \
    && CGO_ENABLED=0 GOOS=linux go install -ldflags '-w -s' github.com/cprates/box/cmd/box \
    && go install golang.org/x/lint/golint \
    && apk add --no-cache git \
    && go install github.com/go-delve/delve/cmd/dlv
